# pull official base image
FROM node:14-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY ./app/package.json ./
COPY ./app/package-lock.json ./
RUN npm install

COPY ./app ./
#RUN npm install --silent
#RUN npm install react-scripts@3.4.1 -g --silent
#RUN npm install && npm run build

CMD ["npm", "start"]